export const projects = [
  {
    number: "01",
    title: "SportLoop",
    subtitle: "校园体育器材借用与维护系统",
    category: "交互设计",
    description: "把器材借用、异常反馈和维护管理连成闭环。",
    labels: ["SYSTEM", "SERVICE", "USER FLOW"],
    size: "wide",
  },
  {
    number: "02",
    title: "Versa 多功能空气炸锅",
    subtitle: "小家电功能与结构优化设计",
    category: "产品设计",
    description: "从用户痛点出发，重构小家电的功能、结构与使用体验。",
    labels: ["OBJECT", "STRUCTURE", "PROTOTYPE"],
    size: "compact",
  },
  {
    number: "03",
    title: "一袭戏服，一种人生",
    subtitle: "中国戏曲元素塔罗牌设计",
    category: "视觉设计",
    description: "将中国戏曲角色与塔罗象征系统转译成像素卡牌。",
    labels: ["VISUAL", "CULTURE", "PROCESS"],
    size: "featured",
    media: {
      src: "./media/tarot-process.mp4",
      poster: "./media/tarot-process-poster.png",
      label: "塔罗牌角色从线稿到完成稿的制作过程",
    },
  },
  {
    number: "04",
    title: "从凝视到亲吻",
    subtitle: "阿根廷队系统协作信息可视化",
    category: "信息可视化",
    description: "用数据和战术关系解释阿根廷队的系统协作。",
    labels: ["DATA", "RELATION", "TACTICS"],
    size: "compact",
  },
  {
    number: "05",
    title: "机械轨道与爬楼机器人",
    subtitle: "结构设计与实体制作",
    category: "机械制作",
    description: "从控制原理、结构设计走到实体制作。",
    labels: ["MECHANISM", "TRACK", "FABRICATION"],
    size: "wide",
  },
  {
    number: "06",
    title: "生长中的记忆",
    subtitle: "可进入的空间装置",
    category: "空间装置",
    description: "用照片、花材、镜面和灯光构建可进入的记忆场景。",
    labels: ["SPACE", "MATERIAL", "MEMORY"],
    size: "wide",
  },
  {
    number: "07",
    title: "AIGC 商业海报实验",
    subtitle: "生成风格与商业传播实验",
    category: "视觉实验",
    description: "探索不同生成风格在商业传播中的表现。",
    labels: ["AIGC", "POSTER", "VISUAL STUDY"],
    size: "compact",
  },
];
